spring.application.name=ChatAppAI
spring.ai.openai.api-key=AIzaSyAbc55jY437d2zAJQHZvrdjYbdxk7mxLhc
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.options.model=gemini-3-flash-preview
